### ISSUE TITLE
Re-enabled TeamCity CD integration

### ISSUE THREAD

**Issue by brianhdk** [vertica-as/Vertica.Utilities#45]
Hi @dgg ,

Hva så - hvordan går det med at lære dansk? 🥇 

I've setup a deploy key to re-enable our TeamCity integration with Vertica Utilities. Just to let you know.

Og udover dét, så håber jeg det går rigtig godt hos dig og familien.

De bedste hilsner
Brian

**Comment by dgg** [comment]
CI for Vertica.Utilities is now on [Appveyor](https://ci.appveyor.com/project/VerticaAS/vertica-utilities). That means, that the package will be public on NuGet's feed instead  of our private feed. I will write everyone to let them know.

As soon as I get my hands on our Team city instance, I will delete the project.
