### ISSUE TITLE
new PaginatedResults throws DivideByZero exception

### ISSUE THREAD

**Issue by RadoslawKozaczuk** [vertica-as/Vertica.Utilities#59]
Hello Sir,

there is a bug in your library.
In case of passing an empty array to PaginatedResults constructor, a DivideByZero exception will occur in the method PageCount line 23.
The calculation is redundant and it should simply create the object by using the parameterless constructor,

Kind Regards
Radek

**Comment by dgg** [comment]
Thanks for your feedback.

I'll have a look and fix it as soon as possible.

Cheers
